name: Docker Build and Push

on:
  push:
    branches: [master]
    tags:
      - "v*"
  pull_request:
    branches: [master]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Stamp version file
        run: make {{cookiecutter.src_dir}}/{{cookiecutter.package_name}}/version.py
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            {%- if cookiecutter.docker_registry != "default" -%}{{cookiecutter.docker_registry}}/{% endif %}{{ cookiecutter.repo_name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            {% raw -%}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            {%- endraw %}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: set up Docker buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          {%- if cookiecutter.docker_registry != "default" -%}registry: {{cookiecutter.docker_registry}}{% endif %}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          file: docker/Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
